/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EchoClient;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;

public class EchoClient {
    public static void main(String[] args) throws Exception {

        Socket socket = new Socket("localhost", 11111);
        PrintWriter out = new PrintWriter(socket.getOutputStream());
        BufferedReader networkIn = new BufferedReader(new InputStreamReader(socket.getInputStream()));
        BufferedReader userIn = new BufferedReader(new InputStreamReader(System.in));
        System.out.println("client on");

        while (true) {
            System.out.print("input:");
            String theLine = userIn.readLine();
            out.println(theLine);
            out.flush();
            if (theLine.equalsIgnoreCase("Quit"))
                break;
            System.out.println("Server push:[ " + networkIn.readLine() + " ]");
        }
        System.out.println("client exit");
        networkIn.close();
        out.close();
        socket.close();
    }
}
