/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EchoServer;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.ServerSocket;
import java.net.Socket;

public class EchoServer {
    public static void main(String[] args) {
	try (ServerSocket serverSocket = new ServerSocket(11111);
                Socket socket = serverSocket.accept();
                PrintWriter out = new PrintWriter(socket.getOutputStream());
                BufferedReader br = new BufferedReader(new InputStreamReader(socket.getInputStream()))) {
 
            System.out.println("server wait...");
            while (true) {
                String msg = br.readLine();
                if (msg.equalsIgnoreCase("Quit"))
                    break;
                System.out.println("client push:[ " + msg + " ]");
                out.println(msg);
                out.flush();
            }
            System.out.println("Server exit..");
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }
}
